{{- if .Values.secretEnv.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fiap-mlet.secretName" . }}
  labels:
    {{- include "fiap-mlet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
