replicaCount: 2

image:
  repository: fiap-mlet-challenge-fase-1
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: fiap-mlet.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 380Mi

startupProbe:
  enabled: true
  httpGet:
    path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

livenessProbe:
  enabled: true
  httpGet:
    path: /health
  initialDelaySeconds: 0
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /health
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/JosueJNLui/fiap-mlet-challenge-fase-1.mlflow"
  MLFLOW_TRACKING_USERNAME: "JosueJNLui"
  MODEL_FLAVOR: "sklearn"
  MODEL_NAME: "Churn_LogReg_Final_Production"
  MODEL_VERSION: "3"
  SCALER_ARTIFACT_PATH: "model_components/scaler.joblib"
  PREDICTION_THRESHOLD: "0.2080"
  LOAD_MODEL_ON_STARTUP: "true"
  DOCS_URL: "/docs"
  REDOC_URL: "/redoc"
  OPENAPI_URL: "/openapi.json"

secretEnv:
  enabled: true
  name: ""
  values:
    MLFLOW_TRACKING_PASSWORD: ""

nodeSelector: {}
tolerations: []
affinity: {}
